# Generated by Django 3.2 on 2024-11-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0016_user_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='vocabulary_icons/'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vocabulary_images/'),
        ),
    ]
